spring:
  application:
    name: onlineshop
  datasource:
    url: jdbc:postgresql://endpointfromaws:5432/postgres #jdbc:postgresql://localhost:5432/onlineshop
    #url: jdbc:postgresql://localhost:5432/onlineshop
    driverClassName: org.postgresql.Driver
    username: lol
    password: kek
    #password: postgres


  jpa:
    # generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
  #datasource:
   # url: jdbc:h2:mem:onlineshop
    show-sql: true
  #  driverClassName: org.h2.Driver
  #  username: sa
  #  password: password
#  jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.amazonaws.xray: DEBUG
